config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :accounts

  root 'accounts#index'
  get '/dashboard' => "accounts#index"
  get '/profile/:username' => 'accounts#profile', as: :profile
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  match "/404", to: "errors#not_found",via: :all 
  match "/500", to: "errors#server_error",via: :all 
  resources :search
  get "displayuser", to: "search#displayuser"
  resources :posts, only: [:new,:create,:show, :destroy]
  resources :comments, only: [:create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts   
  has_many :likes  
  validates_uniqueness_of :email
  validates_uniqueness_of :username
  
  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following 
    Follower.where(following_id: self.id).count
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post 
    belongs_to :account
    belongs_to :parent, class_name: 'Comment', optional: true
    has_many :comments, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

    validates_presence_of :comment 
    validates_presence_of :account_id
    validates_presence_of :post_id

    attr_accessor :return_to

    after_create :increase_post_comment_counter
    after_destroy :decrease_post_comment_counter

    private 

    def increase_post_comment_counter
        Post.find(self.post_id).increment(:total_comments_count).save
    end

    def decrease_post_comment_counter
        Post.find(self.post_id).decrement(:total_comments_count).save
    end
end

app/models/follower.rb
class Follower < ApplicationRecord 
    validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
    has_many :post_hash_tags 
    has_many :posts, through: :post_hash_tags
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post 
    belongs_to :account
    validates_uniqueness_of :post_id, scope: :account_id

    after_create :increase_post_like_counter
    after_destroy :decrease_post_like_counter

    private 

    def increase_post_like_counter
        Post.find(self.post_id).increment(:total_likes_count).save
    end

    def decrease_post_like_counter
        Post.find(self.post_id).decrement(:total_likes_count).save
    end

end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order created_at: :desc }
  has_one_attached :image 
  belongs_to :account
  has_many :post_hash_tags 
  has_many :hash_tags, through: :post_hash_tags 
  has_many :likes
  has_many :comments
  
  before_create :set_active
  validate :image_validation

  def image_validation
    if image.attached?
      if image.blob.byte_size < 1000000
        image.destroy
        errors[:base] << 'Too big'
      elsif !image.blob.content_type.starts_with?('image/')
        image.destroy
        errors[:base] << 'Wrong format'
      end
    else
      image.destroy
      errors[:base] << 'Attach image'
    end

  end
    scope :active, -> {where active: true }
    
    after_commit :create_hash_tags, on: :create 

    def create_hash_tags
        extract_name_hash_tags.each do |name|
            hash_tags.create(name: name)
        end
    end

    def extract_name_hash_tags 
        description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
    end

    private

    def set_active 
        self.active = true 
    end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
    belongs_to :post 
    belongs_to :hash_tag
end

app/models/seach.rb
class Search < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :search
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    before_action :authenticate_account!

    def save_like
        @like = Like.new(post_id: params[:post_id] , account_id: current_account.id)
        @post_id = params[:post_id]
        existing_like = Like.where(post_id: params[:post_id] , account_id: current_account.id)
           respond_to do |format|
            format.js {
                if existing_like.any?
                  existing_like.first.destroy 
                  @success = false 
                elsif @like.save 
                  @success = true 
                else
                  @success = false    
                end
                @post_likes = Post.find(@post_id).total_likes_count
                render "posts/like"
            }
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_post, only: [:show]
    def new 
        @post = Post.new 
    end

    def create 
        @post = Post.new(post_params)
        @post.account_id = current_account.id if account_signed_in? 

        if @post.save
            redirect_to dashboard_path, flash: {notice: "Post was created successfully!" }
        else
            redirect_to new_post_path, flash: { notice: 
                "1.Post was not saved! Please upload file in jpg/jpeg/gif format 
                2.Image size must greater than 1 MB" }
        end
    end

    def show 
        @comment = Comment.new 
        @comments = Comment.includes(:account).where(post_id: @post.id)
    end
    
    def destroy 
        @post = current_account.posts.find(params[:id])
        @post.destroy 

        redirect_to dashboard_path
    end
    private 

    def set_post 
        @post = Post.find(params[:id]) if params[:id].present?
    end
    
    def post_params
        params.require(:post).permit(:image,:description)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  $word = ""
  def index
    $word = params[:query]
    if params[:query].start_with?('#')
      query = params[:query].gsub('#','')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name: query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end 
  end
  
  def displayuser 
    @accounts = Account.where("username like ?", "%#{$word}%")
  end
  
  def show
    @user = User.new
    @accounts = Account.where("username like ?", "%#{params[:query]}%")
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

    def profile_picture account, width, height 
        image_path = account.profile_image.attached? ? account.profile_image : "default-profile.jpg" 
        image_tag(image_path, width: width, height: height, :class => "profile-pic")
    end

    def can_edit_profile? profile_id
        account_signed_in? && current_account.id == profile_id 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_liked_by_user? post_id
        Like.where(post_id: post_id,account_id: current_account.id).any?
    end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/search/_account.html.erb
<% if @posts.exists? or @accounts.exists? %>
   <h1>Users</h1>
 <% else %>
   <h1>Oop!  No users found...</h1>
 <% end %>

<div class = "account-summary">
<% @accounts.each do |account| %>
<div class = "recommended-follower">
    <div class = "row">
      <div class = "col-sm-3 col-2">
        <%= link_to profile_picture(account, 50, 50),profile_path(account.username) %>
      </div>
      <div class = "col-sm-9 col-10">
       <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
       <p class = "text-muted"><%= account.created_at > 2.days.ago ? "New to Instagram" : "Followed by #{account.total_followers} Users" %>
     </div>
  </div>
  <% end %>
  </div>

app/views/search/_post.html.erb
<% @accounts.each do |account| %>
<div class = "recommended-follower">
    <div class = "row">
      <div class = "col-sm-3 col-2">
        <%= link_to profile_picture(account, 50, 50),profile_path(account.username) %>
      </div>
      <div class = "col-sm-2">
       <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
       <p class = "text-muted"><%= account.created_at > 2.days.ago ? "New to Instagram" : "Followed by X users" %>
     </div>
  </div>
  <% end %>

app/views/search/account.html.erb
<% link_to "Users", search_path %>
<% if @accounts.exists? %>
   <h1>Search Results</h1>
 <% else %>
   <h1>Oop!  No Users found...</h1>
 <% end %>
  <div class = "row profile-posts">
 <% @posts.each do |post| %>
<div class = "recommended-follower">
    <div class = "row">
      <div class = "col-sm-3 col-2">
        <%= link_to profile_picture(account, 50, 50),profile_path(account.username) %>
      </div>
      <div class = "col-sm-9 col-10">
       <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
       <p class = "text-muted"><%= account.created_at > 2.days.ago ? "New to Instagram" : "Followed by #{account.total_followers} Users" %>
     </div>
  </div>
  <% end %>
</div> 

app/views/search/displayuser.html.erb
<div class = "btnnav">
   <%= link_to "Posts",  search_index_path(query: $word), class: "signbutton" %>
</div>
<% if @accounts.exists? %>
   <h1>Users</h1>
 <% else %>
   <h1>Oop!  No Users found...</h1>
 <% end %>
  <div class = "row profile-posts">
 
<div class = "account-summary">
<% @accounts.each do |account| %>
<div class = "recommended-follower">
    <div class = "row">
      <div class = "col-sm-3 col-2">
        <%= link_to profile_picture(account, 50, 50),profile_path(account.username) %>
      </div>
      <div class = "col-sm-9 col-10">
       <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
       <p class = "text-muted"><%= account.created_at > 2.days.ago ? "New to Instagram" : "Followed by #{account.total_followers} Users" %>
     </div>
  </div>
  <% end %>
  </div>

app/views/search/index.html.erb
<div class = "btnnav">
 <%= link_to "Users",  displayuser_path, class: "signbutton" %>
 <%= link_to "Posts",  search_index_path(query: $word), class: "signbutton" %>
</div>
<% if @posts.exists? %>
   <h1>Posts</h1>
 <% else %>
   <h1>Oop!  No posts found...</h1>
 <% end %>
  <div class = "row profile-posts">
 <% @posts.each do |post| %>
  <div class = "pics">
    <%= link_to image_tag(post.image, class: "pics"),post_path(post) %>
  </div>
 <% end %>
</div> 

app/views/search/show.html.erb
<% if @accounts.exists? %>
   <h1>Search Results</h1>
 <% else %>
   <h1>Oop!  No Users found...</h1>
 <% end %>
  <div class = "row profile-posts">
 
<div class = "account-summary">
<% @accounts.each do |account| %>
<div class = "recommended-follower">
    <div class = "row">
      <div class = "col-sm-3 col-2">
        <%= link_to profile_picture(account, 50, 50),profile_path(account.username) %>
      </div>
      <div class = "col-sm-9 col-10">
       <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
       <p class = "text-muted"><%= account.created_at > 2.days.ago ? "New to Instagram" : "Followed by #{account.total_followers} Users" %>
     </div>
  </div>
  <% end %>
  </div>