config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :accounts

  root 'accounts#index'
  get '/dashboard' => "accounts#index"
  get '/profile/:username' => 'accounts#profile', as: :profile
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  match "/404", to: "errors#not_found",via: :all 
  match "/500", to: "errors#server_error",via: :all 
  resources :search
  get "displayuser", to: "search#displayuser"
  resources :posts, only: [:new,:create,:show, :destroy]
  resources :comments, only: [:create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts   
  has_many :likes  
  validates_uniqueness_of :email
  validates_uniqueness_of :username
  
  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following 
    Follower.where(following_id: self.id).count
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post 
    belongs_to :account
    belongs_to :parent, class_name: 'Comment', optional: true
    has_many :comments, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

    validates_presence_of :comment 
    validates_presence_of :account_id
    validates_presence_of :post_id

    attr_accessor :return_to

    after_create :increase_post_comment_counter
    after_destroy :decrease_post_comment_counter

    private 

    def increase_post_comment_counter
        Post.find(self.post_id).increment(:total_comments_count).save
    end

    def decrease_post_comment_counter
        Post.find(self.post_id).decrement(:total_comments_count).save
    end
end

app/models/follower.rb
class Follower < ApplicationRecord 
    validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
    has_many :post_hash_tags 
    has_many :posts, through: :post_hash_tags
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post 
    belongs_to :account
    validates_uniqueness_of :post_id, scope: :account_id

    after_create :increase_post_like_counter
    after_destroy :decrease_post_like_counter

    private 

    def increase_post_like_counter
        Post.find(self.post_id).increment(:total_likes_count).save
    end

    def decrease_post_like_counter
        Post.find(self.post_id).decrement(:total_likes_count).save
    end

end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order created_at: :desc }
  has_one_attached :image 
  belongs_to :account
  has_many :post_hash_tags 
  has_many :hash_tags, through: :post_hash_tags 
  has_many :likes
  has_many :comments
  
  before_create :set_active
  validate :image_validation

  def image_validation
    if image.attached?
      if image.blob.byte_size < 1000000
        image.destroy
        errors[:base] << 'Too big'
      elsif !image.blob.content_type.starts_with?('image/')
        image.destroy
        errors[:base] << 'Wrong format'
      end
    else
      image.destroy
      errors[:base] << 'Attach image'
    end

  end
    scope :active, -> {where active: true }
    
    after_commit :create_hash_tags, on: :create 

    def create_hash_tags
        extract_name_hash_tags.each do |name|
            hash_tags.create(name: name)
        end
    end

    def extract_name_hash_tags 
        description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
    end

    private

    def set_active 
        self.active = true 
    end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
    belongs_to :post 
    belongs_to :hash_tag
end

app/models/seach.rb
class Search < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :search
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    before_action :authenticate_account!

    def save_like
        @like = Like.new(post_id: params[:post_id] , account_id: current_account.id)
        @post_id = params[:post_id]
        existing_like = Like.where(post_id: params[:post_id] , account_id: current_account.id)
           respond_to do |format|
            format.js {
                if existing_like.any?
                  existing_like.first.destroy 
                  @success = false 
                elsif @like.save 
                  @success = true 
                else
                  @success = false    
                end
                @post_likes = Post.find(@post_id).total_likes_count
                render "posts/like"
            }
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_post, only: [:show]
    def new 
        @post = Post.new 
    end

    def create 
        @post = Post.new(post_params)
        @post.account_id = current_account.id if account_signed_in? 

        if @post.save
            redirect_to dashboard_path, flash: {notice: "Post was created successfully!" }
        else
            redirect_to new_post_path, flash: { notice: 
                "1.Post was not saved! Please upload file in jpg/jpeg/gif format 
                2.Image size must greater than 1 MB" }
        end
    end

    def show 
        @comment = Comment.new 
        @comments = Comment.includes(:account).where(post_id: @post.id)
    end
    
    def destroy 
        @post = current_account.posts.find(params[:id])
        @post.destroy 

        redirect_to dashboard_path
    end
    private 

    def set_post 
        @post = Post.find(params[:id]) if params[:id].present?
    end
    
    def post_params
        params.require(:post).permit(:image,:description)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

    def profile_picture account, width, height 
        image_path = account.profile_image.attached? ? account.profile_image : "default-profile.jpg" 
        image_tag(image_path, width: width, height: height, :class => "profile-pic")
    end

    def can_edit_profile? profile_id
        account_signed_in? && current_account.id == profile_id 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_liked_by_user? post_id
        Like.where(post_id: post_id,account_id: current_account.id).any?
    end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_account_nav.html.erb
<div class = "icons">
<%= form_with url:search_index_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
  <%= form.text_field :query, value: params[:query], search_id: 1, class: 'form-control mr-sm-2', placeholder: '#search' %>
<% end %>

<li class = "nav-item active">
  <%= link_to "Home", dashboard_path, class: "nav-link" %>
</li>
<li class = "nav-item">
  <%= link_to "New Post", new_post_path, class: "nav-link" %>
</li>
<li class = "nav-item">
  <%= link_to "My Profile", profile_path(current_account.username), class: "nav-link" %>
</li>
<li class = "nav-item">
  <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
</li>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>

<%= javascript_pack_tag 'application', media:'all', 'data-turbolinks-track' => true %>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="icon" type="fa fa-instagram" href="assets/favicon.ico" />
    <%= favicon_link_tag "Instagram-Logo.png"%>
    <title>Instagram</title>

   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a071518e2f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/boxicons/2.1.0/css/boxicons.min.css" integrity="sha512-pVCM5+SN2+qwj36KonHToF2p1oIvoU3bsqxphdOIWMYmgr4ZqD3t5DjKvvetKhXGc/ZG5REYTT6ltKfExEei/Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Web/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-white static-top">
            <div class="container">
                <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">
                    <i class = "fa fa-instagram"></i> Instagram
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <% if account_signed_in? %>
                           <%= render "layouts/account_nav" %>
                        <% else %>
                           <%= render "layouts/public_nav" %>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="mt-5">
                  <%= yield %>
            </div>
        </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  
  </body>
</html>