config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :accounts

  root 'accounts#index'
  get '/dashboard' => "accounts#index"
  get '/profile/:username' => 'accounts#profile', as: :profile
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  match "/404", to: "errors#not_found",via: :all 
  match "/500", to: "errors#server_error",via: :all 
  resources :search
  get "displayuser", to: "search#displayuser"
  resources :posts, only: [:new,:create,:show, :destroy]
  resources :comments, only: [:create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts   
  has_many :likes  
  validates_uniqueness_of :email
  validates_uniqueness_of :username
  
  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following 
    Follower.where(following_id: self.id).count
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post 
    belongs_to :account
    belongs_to :parent, class_name: 'Comment', optional: true
    has_many :comments, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

    validates_presence_of :comment 
    validates_presence_of :account_id
    validates_presence_of :post_id

    attr_accessor :return_to

    after_create :increase_post_comment_counter
    after_destroy :decrease_post_comment_counter

    private 

    def increase_post_comment_counter
        Post.find(self.post_id).increment(:total_comments_count).save
    end

    def decrease_post_comment_counter
        Post.find(self.post_id).decrement(:total_comments_count).save
    end
end

app/models/follower.rb
class Follower < ApplicationRecord 
    validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
    has_many :post_hash_tags 
    has_many :posts, through: :post_hash_tags
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post 
    belongs_to :account
    validates_uniqueness_of :post_id, scope: :account_id

    after_create :increase_post_like_counter
    after_destroy :decrease_post_like_counter

    private 

    def increase_post_like_counter
        Post.find(self.post_id).increment(:total_likes_count).save
    end

    def decrease_post_like_counter
        Post.find(self.post_id).decrement(:total_likes_count).save
    end

end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order created_at: :desc }
  has_one_attached :image 
  belongs_to :account
  has_many :post_hash_tags 
  has_many :hash_tags, through: :post_hash_tags 
  has_many :likes
  has_many :comments
  
  before_create :set_active
  validate :image_validation

  def image_validation
    if image.attached?
      if image.blob.byte_size < 1000000
        image.destroy
        errors[:base] << 'Too big'
      elsif !image.blob.content_type.starts_with?('image/')
        image.destroy
        errors[:base] << 'Wrong format'
      end
    else
      image.destroy
      errors[:base] << 'Attach image'
    end

  end
    scope :active, -> {where active: true }
    
    after_commit :create_hash_tags, on: :create 

    def create_hash_tags
        extract_name_hash_tags.each do |name|
            hash_tags.create(name: name)
        end
    end

    def extract_name_hash_tags 
        description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
    end

    private

    def set_active 
        self.active = true 
    end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
    belongs_to :post 
    belongs_to :hash_tag
end

app/models/seach.rb
class Search < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :search
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_account, only: [:profile]   
    def index 
        followers_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
        followers_ids << current_account.id
        
        @posts = Post.includes(:account).where(account_id: followers_ids).active
        @comment = Comment.new 
        
        following_ids = Follower.where(follower_id: current_account.id).map(&:following_id) 
        following_ids << current_account.id 
        
        @follower_suggestions = Account.where.not(id: following_ids)
    end

    def profile
        @posts = @account.posts.active
    end
    
    def follow_account
        follower_id = params[:follow_id]
        if Follower.create!(follower_id: current_account.id, following_id: follower_id)
          flash[:success] = "Now following user"
        else
           flash[:success] = "Unable to add follower "
        end
        redirect_to dashboard_path
    end

    private

    def set_account 
        @account = Account.find_by_username(params[:username])
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
    def not_found
      render status: 404
    end
    
    def server_error
      render status: 500
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    before_action :authenticate_account!

    def save_like
        @like = Like.new(post_id: params[:post_id] , account_id: current_account.id)
        @post_id = params[:post_id]
        existing_like = Like.where(post_id: params[:post_id] , account_id: current_account.id)
           respond_to do |format|
            format.js {
                if existing_like.any?
                  existing_like.first.destroy 
                  @success = false 
                elsif @like.save 
                  @success = true 
                else
                  @success = false    
                end
                @post_likes = Post.find(@post_id).total_likes_count
                render "posts/like"
            }
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_post, only: [:show]
    def new 
        @post = Post.new 
    end

    def create 
        @post = Post.new(post_params)
        @post.account_id = current_account.id if account_signed_in? 

        if @post.save
            redirect_to dashboard_path, flash: {notice: "Post was created successfully!" }
        else
            redirect_to new_post_path, flash: { notice: 
                "1.Post was not saved! Please upload file in jpg/jpeg/gif format 
                2.Image size must greater than 1 MB" }
        end
    end

    def show 
        @comment = Comment.new 
        @comments = Comment.includes(:account).where(post_id: @post.id)
    end
    
    def destroy 
        @post = current_account.posts.find(params[:id])
        @post.destroy 

        redirect_to dashboard_path
    end
    private 

    def set_post 
        @post = Post.find(params[:id]) if params[:id].present?
    end
    
    def post_params
        params.require(:post).permit(:image,:description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @accounts = account.where("username like ?", "%#{params[:query]}%")
    end 
end

app/helpers/accounts_helper.rb
module AccountsHelper

    def profile_picture account, width, height 
        image_path = account.profile_image.attached? ? account.profile_image : "default-profile.jpg" 
        image_tag(image_path, width: width, height: height, :class => "profile-pic")
    end

    def can_edit_profile? profile_id
        account_signed_in? && current_account.id == profile_id 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_liked_by_user? post_id
        Like.where(post_id: post_id,account_id: current_account.id).any?
    end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_error.html.erb
<!DOCTYPE html>
<html lang="en">


    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Instagram</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>


    <body>
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center">
                <h1 class="display-1 fw-bold">404</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
                <p class="lead">
                    The page you're looking for doesn't exist.
                  </p>
                <a href="http://localhost:3000/accounts/sign_in" class="btn btn-primary">Go Home</a>
            </div>
        </div>
    </body>


</html>

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account| %>
  <div class = "recommended-follower">
    <div class = "row">
      <div class = "col-sm-3 col-2">
        <%= link_to profile_picture(account, 50, 50),profile_path(account.username) %>
      </div>
      <div class = "col-sm-9 col-10">
       <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
          <%= hidden_field_tag :follow_id, account.id %>
          <%= submit_tag "Follow", class: "btn btn-info btn-sm" %>
       <%end%>
       <%= link_to account.username, profile_path(account.username), class: "text-dark" %>
       <p class = "text-muted"><%= account.created_at > 2.days.ago ? "New to Instagram" : "Followed by X users" %>
     </div>
  </div>
<% end %>

app/views/accounts/index.html.erb
<head>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
$(function(){
    
    $(".post-comment").on("click", function(){
      $("#comment_comment").focus();
      });
   
    $(".post-like").on("click", function(){
        var post_id = $(this).data("id");

        $.ajax({
            url: "/post/like/"+post_id,
            method: "GET"
        }).done(function(response){
            console.log(response);
        })
   })
 });
 </script>
 </head>
<div class = "container">
<script src="https://kit.fontawesome.com/769209a579.js" crossorigin="anonymous"></script>
  <div class = "row">
    <div class = "col-8">
       <% @posts.each do |post| %>
         <div class = "insta-post">
          <div class = "post-meta">
            <% if post.account.profile_image.attached? %>
               <%= link_to image_tag(post.account.profile_image, width: "50px" , height:"50px", :class => "profile-pic"),profile_path(post.account.username) %>
            <% else %>
                 <%= link_to profile_path(post.account.username) do %>
                  <img class="profile-pic float-left m-r-10" width="50px" height="50px" src="https://cdn-icons-png.flaticon.com/512/149/149071.png">
                 <% end %>
            <% end %>   
            <%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %>
          </div>
          <%= image_tag(post.image, class: "home-pic")if post.image.attached? %>
          
          <div class = "post-details">
             <div class = "post-actions">
               <i class = "fa fa-heart like-<%= post.id %> <%= 'active' if post_liked_by_user?(post.id) %>fa-2x post-like" data-id= "<%= post.id %>"></i>
               <%= link_to post_path(post.id) do %>
                 <i class = "fa fa-comment fa-2x post-comment"></i>
               <% end %>
            </div>
             <% if post.total_likes_count.present? and post.total_likes_count != 0 %>
                <p><strong id = "post-<%= post.id %>-likes"><%= post.total_likes_count %> likes</strong></p>
              <% end %>
             <p><strong id = "post-<%= post.id %>-comments"><%= link_to post.account.username,profile_path(post.account.username), class: "text-dark" %></p> </strong>
             
             <% post.description.to_s.split(' ').each do |word| %>
                  <% if word.start_with?('#') %>
                    <%= link_to word, search_index_path(query: word) %>
                  <%else %>
                    <%= word %>
                  <%end %>
              <% end %>
             <p class = "text-muted" ><%= time_ago_in_words post.created_at %> ago </p>
             <%= render "posts/comments",  post: post, comments: Comment.where(parent_id: nil).includes(:account).where(post_id: post.id).order(id: :desc).limit(2) %>
             <div class = "sub-comment">
              <%= render "posts/comments",  post: post, comments: Comment.where(parent_id: :comment_id).includes(:account).where(post_id: post.id).order(id: :desc).limit(2) %>
             </div>
            <%= link_to post_path(post.id) do %>
                 <% if post.total_comments_count.present? and post.total_comments_count != 0 %>
                   <span class = "com"><p>View all <%= post.comments.count %> comments</p></span>
                  <% end %> 
              <% end %>
          </div>
           <div class = "comment-box">
            <%= form_for @comment do |f| %>
              <%= f.hidden_field :post_id, value: post.id %>
              <div class = "input-group-append">
               <%= f.text_field :comment, placeholder: "Add a comment...", class: "form-control post-comment" %>
              </div>
              <div class = "input-group-append"> 
              <%= f.submit "Post", class: "btn btn-success float-right" %>
              </div>
            <% end %>
            </div>
        </div>
    <% end %>
    </div> 
    <div class = "col-4">
       <div class = "account-summary">
        <p class ="m-0">
         <% if current_account.profile_image.attached? %>
            <%= link_to image_tag(current_account.profile_image, width: "50px", height:"50px", :class => "profile-pic float-left m-r-10"),profile_path(current_account.username) %>
         <% else %>
            <%= link_to profile_path(current_account.username) do %>
               <img class="profile-pic float-left m-r-10" width="50px" height="50px" src="https://cdn-icons-png.flaticon.com/512/149/149071.png">
            <% end %>
         <% end %>  
         <strong><%= current_account.username %></strong><br />
         <%= current_account.full_name %>
        </p> 
       </div>
       <div class = "follower-suggestions">
       <p class = "text-muted"><strong>Suggestions for you</strong></p>
       <%= render "accounts/follower_suggestions" %>
       </div>
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-4">
        <%= profile_picture @account, 200, 200 %>
    </div>
    <div class = "col-8 text-left">
      <h1><%= @account.full_name %></h1>
      <div class = "row" >
       <div class = "col-6">
        <%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-muted btn-custom float-right" if can_edit_profile?(@account.id) %>
       </div>
      </div> 
      <div class = "row profile-stats">
       <div class = "col-4">
         <%= @account.posts.count %> posts
       </div>
        <div class = "col-4">
          <%= @account.total_followers %> followers 
         </div>
        <div class = "col-4">
          <%= @account.total_following %> following 
         </div>
      </div>

      <p><%= @account.full_name %></p>
      <%= simple_format @account.description %>
      <p><%= link_to @account.website if @account.website.present? %></p>
    </div>
 </div> 
 <div class = "row profile-posts">
    <% @posts.each do |post| %>
      <div  class = "col-3">
       <div class = "pics">
          <%= link_to image_tag(post.image, class: "pics"),post_path(post) %>
        </div>
       </div>
    <%end%>
 </div>
</div>      